Repository KIA-PROGRAMMING-38/JKC-FallguysProject, pull requests merged in 2023-06, with the labels that each got.

#15 [Feat] Login 씬과 로비 씬 연동
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/기능-개발.md
  .github/ISSUE_TEMPLATE/버그-제보.md
  .github/ISSUE_TEMPLATE/에셋-추가.md
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/6/064c579a8bc4d42a4719f22c8ee2ecad87626c38
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/a/0afdf4cac4a01f82522f5651b71159270332eeca
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/b/0b2b41ad1d99992f213582f6b074a7004d2c4164
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/3/3/33079ae0b616c5975a68bc019aad37baabab76ca
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/5/6/568d5b8d6be13daa72be2859c554bfe5f73d2859
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/2/a2a48346243bcb24039e2896f28969c34d928f1a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/4/a49250cda5394273118aa036580351cf8fffef2a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/c/f/cfd57adb4613d2aae7578463aacd8d37cb3c1d8f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/e/0/e025a0be4f5bb78c03598e8aa7fa2ebc473507cf
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/6/064c579a8bc4d42a4719f22c8ee2ecad87626c38
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/a/0afdf4cac4a01f82522f5651b71159270332eeca
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/b/0b2b41ad1d99992f213582f6b074a7004d2c4164
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/3/3/33079ae0b616c5975a68bc019aad37baabab76ca
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/5/6/568d5b8d6be13daa72be2859c554bfe5f73d2859
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/a/2/a2a48346243bcb24039e2896f28969c34d928f1a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/a/4/a49250cda5394273118aa036580351cf8fffef2a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/c/f/cfd57adb4613d2aae7578463aacd8d37cb3c1d8f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/e/0/e025a0be4f5bb78c03598e8aa7fa2ebc473507cf
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/00_Login.unity
  JKC_Fallguys/Assets/Jinsoo/01_Lobby.unity
  JKC_Fallguys/Assets/Jinsoo/01_Lobby.unity.meta
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/GameIntialize.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginPanelPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginPanelPresenter.cs.meta
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginPanelView.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginPanelViewController.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/LoginSceneModel.cs.meta
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/PhotonLoginManager.cs
  JKC_Fallguys/Assets/Jinsoo/Script/00_Login/PhotonLoginManager.cs.meta
  JKC_Fallguys/Assets/Jinsoo/Script/Utility/Singleton.meta
  JKC_Fallguys/Assets/Jinsoo/Script/Utility/Singleton/SingletonMonoBehaviour.cs
  JKC_Fallguys/Assets/Jinsoo/Script/Utility/Singleton/SingletonMonoBehaviour.cs.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Manager.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Manager/PhotonLoginManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Manager/PhotonLoginManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/UI/Scene_Login/LoginPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/Scene_Login/LoginPanelViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Temp/Capsule.prefab
  JKC_Fallguys/Assets/Resources/UI/Global/Panel/UI_BasicPanel_4K.png.meta
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#16 [Chore] README.me 파일 업데이트
  README.md
Labels: chore

#18 Jinsoo/etc
  .github/ISSUE_TEMPLATE/기능-개발.md
  .github/ISSUE_TEMPLATE/버그-제보.md
  .github/ISSUE_TEMPLATE/에셋-추가.md
  README.md
Labels: chore

#19 [Chore] github 세팅 수정
  README.md
Labels: chore

#20 [Feat] DataManager 구현
  JKC_Fallguys/Assets/Jinsoo/DataManager.cs
  JKC_Fallguys/Assets/Jinsoo/DataManager.cs.meta
Labels: enhancement

#34 [Feat] Player Jump
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpStartState.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpSubState.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpingState.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerPhysicsController.cs
Labels: enhancement

#35 [Feat] Player Fall
  JKC_Fallguys/Assets/Huiji/Character/Player.controller
  JKC_Fallguys/Assets/Huiji/Player.unity
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/FallState.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerPhysicsController.cs
  JKC_Fallguys/ProjectSettings/TagManager.asset
Labels: enhancement

#37 [Feat] Player Recovery
  JKC_Fallguys/Assets/Huiji/Player.unity
  JKC_Fallguys/Assets/Huiji/Prefabs/Mesh_FruitChute_BumperShape_Triangle_Large.prefab
  JKC_Fallguys/Assets/Huiji/Prefabs/Mesh_FruitChute_BumperShape_Triangle_Large.prefab.meta
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerInput.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/RecoveryState.cs
  JKC_Fallguys/Assets/Jinsoo/Mesh.meta
  JKC_Fallguys/Assets/Jinsoo/Mesh/Mesh_FruitChute_BumperShape_Triangle_Large.obj
  JKC_Fallguys/Assets/Jinsoo/Mesh/Mesh_FruitChute_BumperShape_Triangle_Large.obj.meta
  JKC_Fallguys/Assets/Jinsoo/ObstacleBumper.cs
  JKC_Fallguys/Assets/Jinsoo/ObstacleBumper.cs.meta
Labels: enhancement

#40 [Refactor] MatchingStandby 씬 오브젝트 동적 생성으로 로직 변경
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/4/0404ff141f47528a4473aa4c393fc61d4db7f8cd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/2/c/2c2ec2c0b3ddce4eb5c6d192dcc4dfd1aafe2121
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/5/d/5dd8818e4ba2a03a15aec95a2064ed21850feb80
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/4/0404ff141f47528a4473aa4c393fc61d4db7f8cd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/2/c/2c2ec2c0b3ddce4eb5c6d192dcc4dfd1aafe2121
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/5/d/5dd8818e4ba2a03a15aec95a2064ed21850feb80
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/02/LineEffect.cs
  JKC_Fallguys/Assets/Jinsoo/02/LineEffectPool.cs
  JKC_Fallguys/Assets/Jinsoo/02/LineEffectPooler.cs
  JKC_Fallguys/Assets/Jinsoo/02/MatchingStandbySceneInitializer.cs
  JKC_Fallguys/Assets/Jinsoo/02/RespawnZone.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/Object/ReleaseZone.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/CurrentParticipantsViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/CurrentParticipantsViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/EnterLobbyFromMatchingViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/EnterLobbyFromMatchingViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ReturnButtonViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ReturnButtonViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/RotaitionFaceIconViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/RotaitionFaceIconViewController.prefab.meta
Labels: enhancement

#54 [Feat] GameResult Scene -> Lobby Scene 전환
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Dive.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Dive/DiveStartState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Dive/DiveStartState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Dive/GetUpState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Dive/GetUpState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Grab.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Grab/AttempingGrabState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Grab/AttempingGrabState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Grab/GrabState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Grab/GrabState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpStartState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpStartState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpSubState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpSubState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpingState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpingState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/LandingState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/LandingState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/MovementState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/MovementState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/RecoveryState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/RecoveryState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInput.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInput.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs.meta
  JKC_Fallguys/Assets/7_InputSystems.meta
  JKC_Fallguys/Assets/7_InputSystems/PlayerActions.inputactions
  JKC_Fallguys/Assets/7_InputSystems/PlayerActions.inputactions.meta
  JKC_Fallguys/Assets/Huiji/Character/Animator/FG_Idle_Qualification01.anim
  JKC_Fallguys/Assets/Huiji/Character/Animator/FG_Idle_Qualification01.anim.meta
  JKC_Fallguys/Assets/Huiji/Meshes/UI/collisionMesh_sideWalls_03.obj
  JKC_Fallguys/Assets/Huiji/Meshes/UI/collisionMesh_sideWalls_03.obj.meta
  JKC_Fallguys/Assets/Huiji/Scene.meta
  JKC_Fallguys/Assets/Huiji/Scene/06_GameResult.unity
  JKC_Fallguys/Assets/Huiji/Scene/06_GameResult.unity.meta
  JKC_Fallguys/Assets/Huiji/Scene/Player.unity
  JKC_Fallguys/Assets/Huiji/Scene/Player.unity.meta
  JKC_Fallguys/Assets/Huiji/Scripts/Player.meta
  JKC_Fallguys/Assets/Huiji/Scripts/System.meta
  JKC_Fallguys/Assets/Huiji/Scripts/System/AnimationEventController.cs
  JKC_Fallguys/Assets/Huiji/Scripts/System/AnimationEventController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/GameResult/ResultViewController.cs
  JKC_Fallguys/Assets/Resources/AnimatorController/VictoryPlayer.controller
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#55 Jinsoo/#53
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/8/a8e37093bc1e11bc3294c0ba6b7501f6bd11900a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/e/6/e68113f33687dc94a53d5025c774ed22743a199d
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/f/1/f1ef845274b799ee39fa9f328e87f42b26732ce2
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/a/8/a8e37093bc1e11bc3294c0ba6b7501f6bd11900a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/e/6/e68113f33687dc94a53d5025c774ed22743a199d
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/f/1/f1ef845274b799ee39fa9f328e87f42b26732ce2
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/TagLiteral.cs
  JKC_Fallguys/Assets/Jinsoo/Canon.cs
  JKC_Fallguys/Assets/Jinsoo/Fruit.cs
  JKC_Fallguys/Assets/Jinsoo/FruitPrefabRegistry.cs
  JKC_Fallguys/Assets/Jinsoo/ObstacleBumper.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Canon.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Canon.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/CanonController.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/CanonController.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Fruit.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Fruit.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitChuteReleaseZone.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitChuteReleaseZone.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPool.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPool.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPooler.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPooler.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPrefabRegistry.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/FruitPrefabRegistry.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TmpScript/MapFruitChuteController.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/MapFruitChuteController.cs.meta
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Apple.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Banana.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Log.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Orange.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Strawberry.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Watermelon.prefab
  JKC_Fallguys/Assets/StageSceneInitializer.cs
  JKC_Fallguys/Assets/StageSceneInitializer.cs.meta
Labels: enhancement

#58 [Feat] FruitChute의 컨베이어벨트 시각 효과 쉐이더 구현
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/8/08b328edc5aa1e0953b607cd01f20245aec36083
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/b/0b7b22286786986ea2b88f8d55b9461d2c7afae0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/6/660d4d6a4e870989e295a37b0d5864319b803b4a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/6/86441ad8885d08cc250ff50ad67c563873cbaffb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/e/9e082ac094df2120dc245f43474014647d63805f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/8/08b328edc5aa1e0953b607cd01f20245aec36083
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/0/b/0b7b22286786986ea2b88f8d55b9461d2c7afae0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/6/660d4d6a4e870989e295a37b0d5864319b803b4a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/6/86441ad8885d08cc250ff50ad67c563873cbaffb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/9/e/9e082ac094df2120dc245f43474014647d63805f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/ConveyorBeltShaderGraph.shadergraph
  JKC_Fallguys/Assets/Jinsoo/ConveyorBeltShaderGraph.shadergraph.meta
  JKC_Fallguys/Assets/Jinsoo/ConveyorBeltShaderMaterial.mat
  JKC_Fallguys/Assets/Jinsoo/ConveyorBeltShaderMaterial.mat.meta
  JKC_Fallguys/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#60 [Refactor] Stage 씬 게임 오브젝트 동적생성으로 로직 리팩토링
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/03_Stage.unity
  JKC_Fallguys/Assets/Jinsoo/ConveyorBeltShaderGraph.shadergraph
  JKC_Fallguys/Assets/Jinsoo/StageSceneInitializer.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Canon.cs
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Banana.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/Fruits/Watermelon.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/MapFruitChute.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PhotonStageSceneEventManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PhotonStageSceneEventManager.prefab.meta
Labels: enhancement

#68 Jinsoo/#65
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/3/e/3e5e92ecbee6b5e8582c313ff1acbeae3a02dfb0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/f/6ff13450df0cfa717f77e4df2a8d08cd45e6d24c
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/7/0/70477362fa9623f8dc8857fe492b28fd55c1cccf
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/e/9e082ac094df2120dc245f43474014647d63805f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/1/5/155a156dfd6769cc6cb969363be4992b651f3295
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/3/e/3e5e92ecbee6b5e8582c313ff1acbeae3a02dfb0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/f/6ff13450df0cfa717f77e4df2a8d08cd45e6d24c
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/7/0/70477362fa9623f8dc8857fe492b28fd55c1cccf
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/a/8af7c70f8fb3b930507796d5b7a87f76deaaefab
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/9/e/9e082ac094df2120dc245f43474014647d63805f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement

#84 [Refactor] 캐릭터의 스크립트에 photonView.IsMine를 추가
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/5/c/5c5bc0d39135aed76ba733b560bf6a3b833a104b
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/9/69c27d42348296689e26bf1aa589ad086a683d02
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/9/991709d3b53136135e2184b786275fbd923b247b
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/5/c/5c5bc0d39135aed76ba733b560bf6a3b833a104b
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/9/69c27d42348296689e26bf1aa589ad086a683d02
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/9/9/991709d3b53136135e2184b786275fbd923b247b
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInput.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/Huiji/Scenes/06_GameResult.unity
  JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/_legendHoop.unitypackage.meta
  JKC_Fallguys/Assets/fruitchute_.unitypackage.meta
  JKC_Fallguys/ProjectSettings/ProjectSettings.asset
  JKC_Fallguys/ProjectSettings/TagManager.asset
Labels: enhancement

#86 [Feat] GoalPanel 오브젝트 구성
  JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelPresenter.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelPresenter.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelView.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelView.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelViewController.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/StageModel.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/StageModel.cs.meta
  JKC_Fallguys/Assets/Resources/UI/03_Stage/Tips.png.meta
  JKC_Fallguys/Assets/_legendHoop.unitypackage.meta
  JKC_Fallguys/Assets/fruitchute_.unitypackage.meta
Labels: enhancement

#88 [Feat] Entry Counter UI
  JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterPresenter.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterPresenter.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterView.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterView.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterViewController.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Resources/UI/03_Stage/Timer_1.png.meta
Labels: enhancement

#89 [Feat] GameLoading 씬의 Random Pick 씬 Main Image 연출 구현
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/d/6/d6ef6ee7d24bb560829d2bf80246960245d5e91f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/d/6/d6ef6ee7d24bb560829d2bf80246960245d5e91f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/05_GameLoading.unity
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/HorizontalRendererView.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/LoadingSceneSplashArtCardPooler.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/MatchingStandbyBackgroundImage.prefab
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/SplashArtRegistry.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/Canon.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/GameLoadingRandomPanel.cs
  JKC_Fallguys/Assets/Jinsoo/TmpScript/GameLoadingRandomPanel.cs.meta
  JKC_Fallguys/Assets/_legendHoop.unitypackage.meta
  JKC_Fallguys/Assets/fruitchute_.unitypackage.meta
Labels: enhancement

#91 [Feat] GameLoading 씬의 Random Pick UI 시작과 끝에 화면 연출 추가
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/05_GameLoading.unity
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingRandomPanel.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingRandomPanel.cs.meta
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingSceneModel.cs.meta
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/LoadingSceneSplashArtCard.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/LoadingSceneSplashArtCardPooler.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenPresenter.cs.meta
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenView.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenView.cs.meta
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenViewController.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenViewController.cs.meta
Labels: enhancement

#94 [Feat] GameLoading 씬의 Map Information UI 화면 게임오브젝트 구성
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/1/c/1c6daf3e2bba29ea86fb5533675be5766c4f7bf7
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/2/e/2e2ffd4cd6e22a13dcaac6ebffa0dfbedd5cd849
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/4/9/49823c243abe0f9e3bedb4f80106a715934a39c7
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/7/0/708f04e450678fc8c27025bf2706aa062c00ddd2
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/3/93c5e8b33fa26927edfcc4fbe1bd6524bd860f05
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/7/977241db214966ec7e81e6b2ec266de62722e54a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/b/d/bd6c77fe73417afa2ba973b9f5eee45c2c0fdac5
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/c/1/c10920d1d8890f02dd236796523e97ecca28f2f5
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/c/8/c89699e79c4a5798b3a5de6c181577e536633d0c
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/d/6/d6ef6ee7d24bb560829d2bf80246960245d5e91f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/d/7/d77b4e7849842bfba46e0500ffcd892637ca20f6
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/e/2/e2995af3c60f16d3ecc31bc349087798dc66539a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/f/0/f0bd965074c95c058907f9901f23432ac9f4aa0d
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/f/2/f28463c6f0e81aa88affa114579414bdda81ef3e
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/1/c/1c6daf3e2bba29ea86fb5533675be5766c4f7bf7
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/2/e/2e2ffd4cd6e22a13dcaac6ebffa0dfbedd5cd849
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/4/9/49823c243abe0f9e3bedb4f80106a715934a39c7
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/6/3/635a698a027294f08466d09c727361d8f37782f0
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/7/0/708f04e450678fc8c27025bf2706aa062c00ddd2
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/9/3/93c5e8b33fa26927edfcc4fbe1bd6524bd860f05
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/9/7/977241db214966ec7e81e6b2ec266de62722e54a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/b/d/bd6c77fe73417afa2ba973b9f5eee45c2c0fdac5
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/c/1/c10920d1d8890f02dd236796523e97ecca28f2f5
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/c/8/c89699e79c4a5798b3a5de6c181577e536633d0c
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/d/6/d6ef6ee7d24bb560829d2bf80246960245d5e91f
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/d/7/d77b4e7849842bfba46e0500ffcd892637ca20f6
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/e/2/e2995af3c60f16d3ecc31bc349087798dc66539a
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/f/0/f0bd965074c95c058907f9901f23432ac9f4aa0d
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/f/2/f28463c6f0e81aa88affa114579414bdda81ef3e
  JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/05_GameLoading.unity
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/Test.unity
  JKC_Fallguys/Assets/Jinsoo/Test.unity.meta
Labels: enhancement

#95 [Feat] Round Result Scene 오브젝트 구성
  JKC_Fallguys/Assets/Huiji/Scenes/03_RoundResult.unity
  JKC_Fallguys/Assets/Huiji/Scenes/03_RoundResult.unity.meta
  JKC_Fallguys/Assets/fruitchute_.unitypackage.meta
Labels: enhancement

#101 [Refactor] GameLoading 씬 오브젝트 동적 생성으로 로직 변경
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/04_GameLoading.unity
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingSceneInitializer.cs.meta
  JKC_Fallguys/Assets/Jinsoo/04_GameLoading/GameLoadingSceneManager.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/GameLoadingSceneManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/GameLoadingSceneManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingBackgroundImage.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingBackgroundImage.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingMainPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingMainPanelViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/HorizontalRendererViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/HorizontalRendererViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/MapInformationViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/MapInformationViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/WhiteScreenViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/WhiteScreenViewController.prefab.meta
Labels: enhancement

#107 [Feat] RoundResult 씬 UI MVRP 스크립트 로직 구현
  JKC_Fallguys/Assets/Huiji/Character/Image.controller
  JKC_Fallguys/Assets/Huiji/Character/Image.controller.meta
  JKC_Fallguys/Assets/Huiji/Scenes/03_RoundResult.unity
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene.meta
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/ResultRoundSetupManager.cs
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/ResultRoundSetupManager.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultPresenter.cs
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultPresenter.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultView.cs
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultView.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultViewController.cs
  JKC_Fallguys/Assets/Huiji/Scripts/RoundResultScene/RoundResultViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/FallGuyData.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/FallGuyData.cs.meta
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/RoundResultSceneModel.cs.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/GameResultAnimator.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/GameResultAnimator/LosePlayer.overrideController
  JKC_Fallguys/Assets/Resources/AnimatorController/GameResultAnimator/LosePlayer.overrideController.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/GameResultAnimator/VictoryPlayer.controller
  JKC_Fallguys/Assets/Resources/AnimatorController/GameResultAnimator/VictoryPlayer.controller.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator1.controller
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator1.controller.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator2.overrideController
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator2.overrideController.meta
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator3.overrideController
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator3.overrideController.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/05_RoundResult.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/05_RoundResult/RoundResultFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/05_RoundResult/RoundResultFallGuy.prefab.meta
Labels: enhancement

#109 [Fix] Card UI Move Animation Fix
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCard.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCardPooler.cs
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/etc/_legendHoop.unitypackage.meta
  JKC_Fallguys/Assets/Jinsoo/etc/fruitchute_.unitypackage.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/LoadingSceneSplashArtCard.prefab
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: Fix

#116 후프의 전설 Skybox를 배치함
  JKC_Fallguys/Assets/3_Art/SkyBox/ColorSkies/Skies/Sky_2.mat
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/Legend_Hoop/Legend_Hoop.unity
Labels: enhancement

#131 [Feat] Exit Stage Panel 구현
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/TestScript.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/TestScript.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/ExitButtonViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageExitPanelViewController.prefab
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#132 [Feat] FruitChute의 과일들 탄성 추가
  JKC_Fallguys/Assets/Resources/Fruit_Apple.prefab
  JKC_Fallguys/Assets/Resources/Fruit_Banana.prefab
  JKC_Fallguys/Assets/Resources/Fruit_Log.prefab
  JKC_Fallguys/Assets/Resources/Fruit_Orange.prefab
  JKC_Fallguys/Assets/Resources/Fruit_Strawberry.prefab
  JKC_Fallguys/Assets/Resources/Fruit_Watermelon.prefab
Labels: enhancement

#137 [Feat] Configs 게임오브젝트 구성
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity.meta
  JKC_Fallguys/Assets/Photon.meta
  JKC_Fallguys/Assets/Photon/PhotonLibs.meta
  JKC_Fallguys/Assets/Photon/PhotonLibs/Metro.meta
  JKC_Fallguys/Assets/Photon/PhotonLibs/netstandard2.0.meta
Labels: enhancement

#138 [Feat]깃발 배치 완료
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/JumpClub.unity
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Flag.mat
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Flag.mat.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/FlagBase_Support.mat
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/FlagBase_Support.mat.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Mesh_JumpClub/Test.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Mesh_JumpClub/Test/ENV_flagBase_MO #683826.obj
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Mesh_JumpClub/Test/ENV_flagBase_MO #683826.obj.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Mesh_JumpClub/Test/Mesh_FruitChute_RotatingFlag_MO.obj
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Mesh_JumpClub/Test/Mesh_FruitChute_RotatingFlag_MO.obj.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Prefabs/Flag.prefab
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Prefabs/Flag.prefab.meta
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Prefabs/GreenLowerBar.prefab
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Texture2D_JumpClub/Texture2D_MeshTexture_FruitChute_RotatingFlag_Flag_AM.png
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Texture2D_JumpClub/Texture2D_MeshTexture_FruitChute_RotatingFlag_Flag_AM.png.meta
Labels: enhancement

#140 [Feat] 환경설정 UI MVRP 스크립트 작성
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
Labels: enhancement

#144 [Feat] Settings MVRP 스크립트 구성
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
Labels: enhancement

#148 [Feat] Stage 씬 UI 병합
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInput.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/TestScript.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStartPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/Stage Scene Initializer.prefab
  JKC_Fallguys/Assets/Jinsoo/Stage Scene Initializer.prefab.meta
  JKC_Fallguys/Assets/Jinsoo/TestStage.unity
  JKC_Fallguys/Assets/Jinsoo/TestStageInitializer.cs
  JKC_Fallguys/Assets/Jinsoo/TestStageInitializer.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestStageMi.unity
  JKC_Fallguys/Assets/Jinsoo/TestStageMi.unity.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageExitPanelViewController.prefab
Labels: enhancement

#156 [Feat] HowToPlay Panel 구현
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingStandbyPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
  JKC_Fallguys/Assets/Resources/UI/Global/Pattern/UI_ZigZagTileablePattern.png.meta
  JKC_Fallguys/Assets/Resources/UI/Global/Texture2D_UI_Global_InputKeyCode.png.meta
Labels: enhancement

#157 [Feat] Configs 오브젝트 구성
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayView.cs
  JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
  JKC_Fallguys/Assets/Huiji/Scenes/Settings.unity
  JKC_Fallguys/Assets/Huiji/Scenes/Settings.unity.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/Customization/CostumeViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/Customization/CostumeViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs.meta
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/ActionUI_js_arrow_01.png
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/ActionUI_js_arrow_01.png.meta
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/ActionUI_js_arrow_02.png
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/ActionUI_js_arrow_02.png.meta
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/UI_RoundedPanel3Large_Image.png
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/UI_RoundedPanel3Large_Image.png.meta
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/UI_settings_cogs_1080p.png
  JKC_Fallguys/Assets/Resources/UI/01_Lobby/Configs/UI_settings_cogs_1080p.png.meta
Labels: enhancement

#160 [Refactor] PersonalIndex를 ActorNumber로 변경, 점수 합계 로직 변경
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/GoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/PlayerData.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerData.cs.meta
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#166 [Feat] FruitChute 맵에서의 플레이어 리스폰 구현
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/RespawnZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteReleaseZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/RotationFaceIconPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Legend_Hoop_Map.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Legend_Hoop_Map.prefab.meta
Labels: enhancement

#170 [Feat] Costume UI Button Navigation
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume.meta
  JKC_Fallguys/Assets/Jinsoo/Customization.unity
Labels: enhancement

#172 Jinsoo/#153
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerData.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerData.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteReleaseZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/ObstacleBumper.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubMapInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubMapInitializer.cs.meta
  JKC_Fallguys/Assets/Huiji/Character/Animator/Player.controller
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
Labels: enhancement

#173 [Feat] 맵 데이터 클래스 구현
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerData.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/MapData.cs
  JKC_Fallguys/Assets/Jinsoo/MapData.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestJson.cs
  JKC_Fallguys/Assets/Jinsoo/TestJson.cs.meta
  JKC_Fallguys/Assets/Resources/JSON.meta
  JKC_Fallguys/Assets/Resources/JSON/MapData_00.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_00.json.meta
  JKC_Fallguys/Assets/Resources/JSON/MapData_01.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_01.json.meta
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json.meta
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/00_Splash_FruitChute.png
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/00_Splash_FruitChute.png.meta
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/01_Splash_HoopsLegends.png
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/01_Splash_HoopsLegends.png.meta
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/02_Splash_JumpClub.png
  JKC_Fallguys/Assets/Resources/UI/04_GameLoading/SplashArts/02_Splash_JumpClub.png.meta
Labels: enhancement

#175 [Chore] JSON 파일에 맵 정보 업데이트
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/MapData.cs
  JKC_Fallguys/Assets/Resources/JSON/MapData_00.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_01.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab.meta
Labels: enhancement

#176 Jinsoo/#162
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/MapData.cs
  JKC_Fallguys/Assets/Jinsoo/MapSelectionManager.cs
  JKC_Fallguys/Assets/Jinsoo/MapSelectionManager.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestJson.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/JSON/MapData_00.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_01.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/MapSelectionManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/MapSelectionManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingMainPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/HorizontalRendererViewController.prefab
Labels: enhancement

#177 [Feat] Costume Button 하이라이트, Scriptable Object 추가
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeData.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeData.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeViewController.cs.meta
  JKC_Fallguys/Assets/Jinsoo/Customization.unity
  JKC_Fallguys/Assets/Resources/Costume.meta
  JKC_Fallguys/Assets/Resources/Costume/Abyss.asset
  JKC_Fallguys/Assets/Resources/Costume/Abyss.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Blue.asset
  JKC_Fallguys/Assets/Resources/Costume/Blue.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Grape.asset
  JKC_Fallguys/Assets/Resources/Costume/Grape.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Lemon.asset
  JKC_Fallguys/Assets/Resources/Costume/Lemon.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Melon.asset
  JKC_Fallguys/Assets/Resources/Costume/Melon.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Orange.asset
  JKC_Fallguys/Assets/Resources/Costume/Orange.asset.meta
  JKC_Fallguys/Assets/Resources/Costume/Strawberry.asset
  JKC_Fallguys/Assets/Resources/Costume/Strawberry.asset.meta
Labels: enhancement

#178 Jinsoo/#163
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/GoalPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/GoalPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/GoalPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStartPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStartView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStartViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/MapData.cs
  JKC_Fallguys/Assets/Jinsoo/TestJson.cs
  JKC_Fallguys/Assets/Jinsoo/TestJson.cs.meta
  JKC_Fallguys/Assets/Resources/JSON/MapData_00.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_01.json
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PurposePanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PurposePanelViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageStartViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/UI/GameLoadingMainPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#179 [Feat] HoopLegend 맵의 Hoop를 통과할 시, 파티클 이미지 추가
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_01.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_02.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_03.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_04.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_05.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_06.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_07.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_08.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_09.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_10.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_11.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_12.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_13.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_14.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/CommonHoop_15.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_01.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_02.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_03.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_04.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_05.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_06.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_07.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_08.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/SpecialHoop_09.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/StarEffect.png
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Hoop/StarEffect.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/00_Texture2D_Player_Customize_MaterialColor_Red 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/00_Texture2D_Player_Customize_MaterialColor_Red 1.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/01_Texture2D_Player_Customize_MaterialColor_Orange 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/01_Texture2D_Player_Customize_MaterialColor_Orange 1.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/02_Texture2D_Player_Customize_MaterialColor_Yellow 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/02_Texture2D_Player_Customize_MaterialColor_Yellow 1.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/03_Texture2D_Player_Customize_MaterialColor_Green 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/03_Texture2D_Player_Customize_MaterialColor_Green 1.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/04_Texture2D_Player_Customize_MaterialColor_Blue.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/04_Texture2D_Player_Customize_MaterialColor_Blue.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/05_Texture2D_Player_Customize_MaterialColor_Navy 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/05_Texture2D_Player_Customize_MaterialColor_Navy 1.png.meta
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/06_Texture2D_Player_Customize_MaterialColor_Pupple 1.png
  JKC_Fallguys/Assets/Resources/Textures/PlayerTexture/06_Texture2D_Player_Customize_MaterialColor_Pupple 1.png.meta
Labels: enhancement

#180 [Feat] RoundResult 씬 UI와 네트워크 연동
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/PlayerTextureRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/PlayerTextureRegistry.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/ResultRoundSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/FallGuyData.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/FallGuyData.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/Huiji/Character/Materials/Materials/PlayerMaterial.mat
  JKC_Fallguys/Assets/Huiji/Character/Materials/Materials/PlayerMaterial.mat.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/05_RoundResult/RoundResultFallGuy.prefab
Labels: enhancement

#182 [Feat] Json 파일을 로드하는 제네릭 함수 추가
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs
Labels: enhancement

#185 [Feat] ResultInStage Panel
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageViewController.cs.meta
  JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
  JKC_Fallguys/Assets/Resources/UI/Global/Pattern/UI_CrownRankBgTile_Image.png
  JKC_Fallguys/Assets/Resources/UI/Global/Pattern/UI_CrownRankBgTile_Image.png.meta
Labels: enhancement

#186 [Feat] 환경설정 - Costume UI MVRP 스크립트 작성 (프리팹의 색상 변하게)
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeData.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/Customization.unity
  JKC_Fallguys/Assets/Resources/Costume/Abyss.asset
  JKC_Fallguys/Assets/Resources/Costume/Blue.asset
  JKC_Fallguys/Assets/Resources/Costume/Grape.asset
  JKC_Fallguys/Assets/Resources/Costume/Lemon.asset
  JKC_Fallguys/Assets/Resources/Costume/Melon.asset
  JKC_Fallguys/Assets/Resources/Costume/Orange.asset
  JKC_Fallguys/Assets/Resources/Costume/Strawberry.asset
Labels: enhancement

#190 [Feat] JumpClub 게임 종료 조건 구현
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/GoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubMapInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingStandbyPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/JumpClubController.cs
  JKC_Fallguys/Assets/Jinsoo/JumpClubController.cs.meta
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/StageController.cs
  JKC_Fallguys/Assets/Jinsoo/StageController.cs.meta
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#191 [Feat] HoopLegend 게임 종료 조건 구현
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/System/DataManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/DataManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/System/Manager.meta
  JKC_Fallguys/Assets/1_Scripts/System/MapData.cs
  JKC_Fallguys/Assets/1_Scripts/System/MapData.cs.meta
  JKC_Fallguys/Assets/1_Scripts/System/ObjectTransforms.cs
  JKC_Fallguys/Assets/1_Scripts/System/ObjectTransforms.cs.meta
  JKC_Fallguys/Assets/Jinsoo/HoopLegendController.cs
  JKC_Fallguys/Assets/Jinsoo/HoopLegendController.cs.meta
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#192 [Feat] FruitChute 게임 종료 조건 구현
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/GoalCollider.cs
  JKC_Fallguys/Assets/Jinsoo/FruitChuteController.cs
  JKC_Fallguys/Assets/Jinsoo/FruitChuteController.cs.meta
Labels: enhancement

#195 [Refactor] 스테이지 진입시, UniRx의 오작동을 수정, FruitChute 맵 종료 조건 수정
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#197 [Feat] Costume UI와 Customization UI 연동
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingSceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/Jinsoo/Customization.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/Customization/CostumeViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/Customization/CostumeViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/LobbySceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/Object/MatchingSceneFallGuy.prefab
Labels: enhancement

#199 Jinsoo/#198
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingStandbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/Define/SceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/EnterLobbyFromMatchingPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/EnterLobbyFromMatchingView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/EnterLobbyFromMatchingViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ExitMatchingPanelViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ReturnButtonPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ReturnButtonView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_MatchingStandby/ReturnButtonViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/MatchingSceneModel.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/LobbySceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ExitMatchingPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ExitMatchingPanelViewController.prefab.meta
  README.md
Labels: enhancement

#205 [Feat] Stage에서의 Round Result 팝업 후 사라지는 애니메이션 추가
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageViewController.cs
  JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ResultInStageViewController.prefab
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#207 Jinsoo/#200
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/System/DataManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/FruitChuteController.cs
  JKC_Fallguys/Assets/Jinsoo/HoopLegendController.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/StageInstantiateManager.cs
  JKC_Fallguys/Assets/Jinsoo/StageInstantiateManager.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestNetworkConnector.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Code/PhotonHandler.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageInstantiateManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageInstantiateManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#214 Jinsoo/#211
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/Canon.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
Labels: enhancement

#215 [Feat] HoopLegend 디테일 요소 추가
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/1_Scripts/System/ObjectTransforms.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/Jinsoo/AxeController.cs
  JKC_Fallguys/Assets/Jinsoo/AxeController.cs.meta
  JKC_Fallguys/Assets/Jinsoo/HoopLegendAxe.cs
  JKC_Fallguys/Assets/Jinsoo/HoopLegendAxe.cs.meta
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/JSON/AxeTransformData.json
  JKC_Fallguys/Assets/Resources/JSON/AxeTransformData.json.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/CommonHoop.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/SpecialHoop.prefab
Labels: enhancement

#217 [Feat] 플레이어 상태에 따른 UI와, 라운드 종료시의 UI 연동
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerData.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RoundEnd/RoundEndPresenter.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#219 [Feat] Login Scene 오디오 추가
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/AudioManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/System/DataManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/00_Login/LoginPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LoginSceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Resources/Sounds/Music/MUS_InGame_Jingle.wav
  JKC_Fallguys/Assets/Resources/Sounds/Music/MUS_InGame_Jingle.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/Music/UI_MainMenu_Login.wav
  JKC_Fallguys/Assets/Resources/Sounds/Music/UI_MainMenu_Login.wav.meta
Labels: enhancement
