Repository KIA-PROGRAMMING-38/JKC-FallguysProject, pull requests merged in 2023-07, with the labels that each got.

#228 [Refactor] FruitChute GoalCollider의 로직 수정
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#230 Jinsoo/#229
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: chore

#235 [Feat] GameLoading Scene, Round Result Scene Sound 추가
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/FinalRoundAudioScheduler.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/RoundAudioScheduler.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/FallGuyEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/FallGuyEmoteState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/Resources/AnimatorController/ResultRoundAnimator/FallGuyAnimator1.controller
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_01_3D_Clap.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_01_3D_Clap.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_02_3D_ThumbsUp.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_02_3D_ThumbsUp.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_03_3D_HighFice.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/05_RoundResult/SFX_Emote_03_3D_HighFice.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/SFX_WinnerScreen_WinnerAnim.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/SFX_WinnerScreen_WinnerAnim.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Confeti.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Confeti.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Currency_Obtained.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Currency_Obtained.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Numbers_LP.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Reward/UI_RewardScreen_Numbers_LP.wav.meta
Labels: enhancement

#237 Jinsoo/#234
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/Canon.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab
Labels: enhancement

#248 [Feat] Stage씬에서의 CountDown 시작 타이밍 동기화
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStart/StageStartPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#249 [Bug] 라운드 종료! UI가 모든 클라이언트에서 뜨지 않는 이슈 해결
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: bug

#250 [Feat] PhotonView가 달린 객체가 파괴될 시, 스스로의 photonView를 정리하는 컴포넌트 부착
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs.meta
  JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/2_Scenes/06_GameResult.unity
  JKC_Fallguys/Assets/Jinsoo/PhotonClear.cs
  JKC_Fallguys/Assets/Jinsoo/PhotonClear.prefab
  JKC_Fallguys/Assets/Jinsoo/PhotonClear.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PhotonStageSceneEventManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PhotonStageSceneRoomManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageInstantiateManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/MapSelectionManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/05_RoundResult/SceneChanger.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#251 [Bug] RoundResult 씬에 진입할 때, PlayerName이 정상적으로 UI와 동기화되지 않는 이슈 해결
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs
Labels: bug

#254 [Feat] Game Result Fall Guy SFX 추가
  JKC_Fallguys/Assets/1_Scripts/Scene/06_GameResult/GameResultAudioScheduler.cs
  JKC_Fallguys/Assets/2_Scenes/06_GameResult.unity
  JKC_Fallguys/Assets/FirstEmoteState.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/06_GameResult/GameResultSceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Sounds/SFX/06_GameResult/Lose/SFX_Emote_3D_01_Arm.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/06_GameResult/Lose/SFX_Emote_3D_01_Arm.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/06_GameResult/Lose/SFX_Emote_3D_02_Pirate.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/06_GameResult/Lose/SFX_Emote_3D_02_Pirate.wav.meta
  JKC_Fallguys/Assets/SecondEmoteState.cs
  JKC_Fallguys/Assets/ThirdEmoteState.cs
Labels: enhancement

#255 [Feat] JumpClub 맵의 막대의 속도와 회전 동기화
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/PhotonLoginManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Resources/JSON/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#256 [Feat] 관전 시스템 UI 게임오브젝트 구성
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs.meta
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameView.cs
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameView.cs.meta
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameViewController.cs
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameViewController.cs.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ObservedPlayerNameViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ObservedPlayerNameViewController.prefab.meta
Labels: enhancement

#259 [Fix] Jump관련 Action메소드 PlayerLoopTiming FixedUpdate로 변경
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/Jump/JumpingState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement

#261 Jinsoo/#260
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStart/StageStartPresenter.cs
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Jinsoo/LandscapeViewer.cs
  JKC_Fallguys/Assets/Jinsoo/LandscapeViewer.cs.meta
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs.meta
  JKC_Fallguys/Assets/Jinsoo/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerObserverCamera.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestNetworkConnector.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ObservedPlayerNameViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/LandscapeViewer.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/LandscapeViewer.prefab.meta
Labels: enhancement

#266 [Refactor] StageDataManager 코드 리팩토링 롤백
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#267 [Fix] Lobby UI 활성화 설정
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
Labels: Fix

#270 Jinsoo/#155
  JKC_Fallguys/Assets/1_Scripts/Player/ObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Player/ObserverCamera.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/MovementState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/PhotonLoginManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/ObservingCameraAction.inputactions
  JKC_Fallguys/Assets/Jinsoo/ObservingCameraAction.inputactions.meta
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/COL_PB_FollowTheLeader_Design_Arch (1).obj
  JKC_Fallguys/Assets/Resources/Prefabs/COL_PB_FollowTheLeader_Design_Arch (1).obj.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PlayerObserverCamera.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PlayerObserverCamera.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: enhancement

#274 [Feat] Stage씬에서 사용되는 타이머 UI 구현
  JKC_Fallguys/Assets/1_Scripts/Player/ObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/EntryCounterPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/EntryCounterView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/EntryCounterViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimePresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimeView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimeView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimeViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/EntryCounter/RemainingTimeViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
  JKC_Fallguys/Assets/Jinsoo/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/RemainingTimeViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/RemainingTimeViewController.prefab.meta
Labels: enhancement

#275 [Bug] 마스터 클라이언트가 아닐 경우 게임 시작시 Null Reference 발생 해결
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimeView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimeView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimeViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimeViewController.cs.meta
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: bug, enhancement

#277 [Feat] AudioMixer Settings
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/Object/MatchingSceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Sounds/AudioMixer.mixer
  JKC_Fallguys/Assets/Resources/Sounds/AudioMixer.mixer.meta
Labels: enhancement

#279 [Refactor] 스테이지 시작시 PhotonNetwork.Instantiate 되는 오브젝트들, 세팅
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/LandscapeViewer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/LandscapeViewer.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerObserverCamera.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageController.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameViewController.cs.meta
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/2_Scenes/06_GameResult.unity
  JKC_Fallguys/Assets/7_InputSystems/ObservingCameraAction.inputactions
  JKC_Fallguys/Assets/7_InputSystems/ObservingCameraAction.inputactions.meta
  JKC_Fallguys/Assets/Jinsoo/StageRepository.cs
  JKC_Fallguys/Assets/Jinsoo/StageRepository.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestStageMi.unity
  JKC_Fallguys/Assets/Jinsoo/TestStageMi.unity.meta
  JKC_Fallguys/Assets/Jinsoo/etc.meta
  JKC_Fallguys/Assets/Jinsoo/etc/FruitMap_Prefabs.meta
  JKC_Fallguys/Assets/Jinsoo/etc/FruitMap_Prefabs/MAP.prefab
  JKC_Fallguys/Assets/Jinsoo/etc/FruitMap_Prefabs/MAP.prefab.meta
  JKC_Fallguys/Assets/Jinsoo/etc/FruitMap_Prefabs/Purple_1K_Resolution.mat
  JKC_Fallguys/Assets/Jinsoo/etc/FruitMap_Prefabs/Purple_1K_Resolution.mat.meta
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/PhotonStageSceneEventManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab
Labels: enhancement

#283 [Refactor] HoopLegend Hoop, Axe들 DontDestroyObject로 변경
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs
Labels: bug, enhancement

#284 [Bug] 마스터 클라이언트가 아닌 클라이언트로 후프의 전설 후프 통과시 Null reference 발생 해결
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/Jinsoo/StageRepository.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/CommonHoop.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/SpecialHoop.prefab
Labels: bug, enhancement

#286 [Bug] HoopLegend맵에서 마스터 클라이언트가 아닌 클라이언트가 후프를 통과했을 때, 마스터 클라이언트도 점수를 얻는 현상 수정
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/Legend_Hoop/Scripts_Legend/GoalCheck.cs
Labels: bug, enhancement

#291 [Feat] 골 콜라이더에 닿거나 데드존에 닿을 경우, 플레이어의 프리팹을 끄는 기능 추가
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RoundEnd/RoundEndPresenter.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#292 [Feat] ObservedPlayerName UI 로직 연동
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#293 [Bug] 플레이어가 벽에 부딪히는 경우, 바로 떨어지지 않고 멈칫했다가 떨어지는 버그 해결
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/MovementState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
Labels: bug, enhancement

#294 Huiji/#244
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/VolumeSettings.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/VolumeSettings.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/Huiji/Scenes/Settings.unity
  JKC_Fallguys/Assets/Resources/Sounds/AudioMixer.mixer
Labels: enhancement

#299 [Feat] Player State에 Sound 추가
  JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/Huiji/Character/Character (merge).fbx.meta
  JKC_Fallguys/Assets/Huiji/Scenes/Player.unity
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_01.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_01.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_02.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_02.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_03.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_03.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_04.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Hit/SFX_ElimBoard_CartoonHit_04.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Dive/F_Footsteps_Dive_02.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Dive/F_Footsteps_Dive_02.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Dive/F_Footsteps_Dive_03.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Dive/F_Footsteps_Dive_03.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Fall.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Fall/SFX_ElimBoard_CartoonHit.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Fall/SFX_ElimBoard_CartoonHit.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_02.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_02.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_03.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_03.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_04.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_04.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_05.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_05.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_06.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Player/Jump/F_Footsteps_Jump_Soft_06.wav.meta
Labels: enhancement

#301 [Feat] 과일 대포에서 완주못한 플레이어 참가 점수 추가, 점프 클럽 참가 점수 추가
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/ObstacleBumper.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/CommonHoop.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/SpecialHoop.prefab
Labels: enhancement

#306 [Fix] PlayerObservedName UI 라운드가 끝나면 false 상태로 전환하기
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
Labels: Fix

#307 [Fix] JumpClub맵의 원형 경기장 조립
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
  JKC_Fallguys/Assets/Jinsoo/JumpClubTask.unity
  JKC_Fallguys/Assets/Resources/Mesh/JumpClub/COL_PB_FollowTheLeader_Design_Arch (1).obj
  JKC_Fallguys/Assets/Resources/Mesh/JumpClub/COL_PB_FollowTheLeader_Design_Arch (1).obj.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
Labels: chore, Fix

#308 [Feat] 마우스 커서 변경
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageRepository.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageRepository.cs.meta
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Jinsoo/_TestCursor.png
  JKC_Fallguys/Assets/Jinsoo/_TestCursor.png.meta
  JKC_Fallguys/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#310 [Fix] 관찰 대상이었던 상대가 상태가 변할경우, 대상을 변경하는 로직 구현
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
Labels: enhancement, Fix

#311 Huiji/#300
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/06_GameResult/GameResultAudioScheduler.cs
  JKC_Fallguys/Assets/1_Scripts/System/LobbyAudioScheduler.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/VolumeSettings.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/Huiji/Scenes/Settings.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/00_Login/LoginPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/UI/ConfigsViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/UI/ConfigsViewController.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/06_GameResult/GameResultSceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Sounds/SFX/MoveBox/SFX_OBJ_MovableBlock_Medium_LP.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/MoveBox/SFX_OBJ_MovableBlock_Medium_LP.wav.meta
Labels: enhancement

#312 [Fix] Stage씬 내에서 Exit Button 클릭시 아무런 동작이 안하는 현상 수정
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
  JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ExitButtonViewController.prefab
Labels: Fix

#315 [Refactor] DataManager의 GetGameObject를 제네릭으로 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/LineEffectPool.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingSceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/06_GameResult/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/Define/SceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/System/ResourceManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/ResourceManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCardPool.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/ResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/CountdownSpritesRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/FruitPrefabRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/PlayerTextureRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/SplashArtRegistry.cs
  JKC_Fallguys/Assets/Jinsoo/TestNetworkConnector.cs
  JKC_Fallguys/Assets/Jinsoo/TestNetworkConnector.cs.meta
  JKC_Fallguys/Assets/Jinsoo/TestStageInitializer.cs
  JKC_Fallguys/Assets/Jinsoo/TestStageInitializer.cs.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/06_GameResult/GameResultScenePhotonController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Test.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Test/Player.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Test/Player.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Test/TestNetworkConnector.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Test/TestNetworkConnector.prefab.meta
Labels: enhancement

#317 Jinsoo/#316
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/LineEffectPool.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/06_GameResult/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/System/ResourceManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCardPool.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/ResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/CountdownSpritesRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/FruitPrefabRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/PlayerTextureRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/SplashArtRegistry.cs
Labels: enhancement

#319 [Refactor] ResourceManager의 Instantiate로직 수정
  JKC_Fallguys/Assets/1_Scripts/Scene/00_Login/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/05_RoundResult/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Scene/06_GameResult/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/System/ResourceManager.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Manager.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/00_Login/PhotonLoginManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/00_Login/PhotonLoginManager.prefab.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageAudioManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageAudioManager.prefab.meta
Labels: enhancement

#321 [Feat] UnixTimeHelper 클래스 추가
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs
  JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs.meta
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#323 [Refac] AudioManager 재구성
  JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/System/LobbyAudioScheduler.cs
Labels: enhancement

#324 [Refactor] PhotonNetwork.Time을 이용한 StageRoomManager클래스 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#329 [Refac] Lobby Scene Initializer 경로 Fix
  JKC_Fallguys/Assets/1_Scripts/Manager/ResourceManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/PlayerTextureRegistry.cs
Labels: Fix

#333 [Refac] Stage Scene Initializer 경로 Fix
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
Labels: Fix

#334 [Refac] RoundResult Scene Initializer 경로 Fix
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/3_Art.meta
Labels: Fix

#337 [Refac] GameResult Scene Initializer 경로 Fix
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
Labels: Fix

#338 [Refac] Matching Scene Initializer 경로 재구성
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
Labels: Fix

#341 [Refac] Stage Scene Initializer에서 StageDataManager 의 데이터를 Clear하는 부분 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/2_Scenes/06_GameResult.unity
Labels: enhancement

#343 [Refac] Loading Scene Initializer 경로 재구성
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/3_Art.meta
Labels: Fix

#345 [Refac] Matching씬에 배치된 게임 오브젝트들을 동적으로 생성하도록 로직 변경
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/LineEffectPool.cs
  JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/LineEffectPooler.cs
Labels: enhancement

#347 [Refac] 게임이 돌아가도록, 코드 수정
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCardPool.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/CountdownSpritesRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/SplashArtRegistry.cs
  JKC_Fallguys/Assets/2_Scenes/02_Matching.unity
  JKC_Fallguys/Assets/3_Art.meta
  JKC_Fallguys/Assets/Resources/Data/MapData_00.json
  JKC_Fallguys/Assets/Resources/Data/MapData_01.json
  JKC_Fallguys/Assets/Resources/Data/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/UI/04_GameLoading/LoadingSceneSplashArtCard.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/04_GameLoading/LoadingSceneSplashArtCard.prefab.meta
Labels: Fix

#349 Jinsoo/#348
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
Labels: Fix

#351 [Fix] GameResult씬에서 폴가이들의 애니메이터 경로 수정
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/etc/FirstEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/etc/SecondEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/etc/ThirdEmoteState.cs
Labels: Fix

#354 [Feat] UnixTimeHelper 삭제, PhotonNetworkTimeHelper 클래스 생성, LowerBar클래스 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Jinsoo/PhotonTimeHelper.cs
  JKC_Fallguys/Assets/Jinsoo/PhotonTimeHelper.cs.meta
  JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/PhotonTimeHelper.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/PhotonTimeHelper.prefab.meta
Labels: enhancement

#356 [Refac] AudioManager가 전반적인 사운드를 관리하게 수정, Fall Guy SFX를 Animation Events로 사운드를 재생하게 수정
  JKC_Fallguys/Assets/1_Scripts/Manager/AudioManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationEvents.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationEvents.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/States/FallGuyEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/States/FallGuyEmoteState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/00_Login/LoginPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
  JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/AudioRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/etc/FirstEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/etc/SecondEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/etc/SecondEmoteState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/ThirdEmoteState.cs
  JKC_Fallguys/Assets/1_Scripts/etc/ThirdEmoteState.cs.meta
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
  JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
  JKC_Fallguys/Assets/3_Art.meta
  JKC_Fallguys/Assets/Huiji/Character/Character (merge).fbx.meta
  JKC_Fallguys/Assets/Resources/Animation/Controller/GameResultAnimator/VictoryPlayer.controller
  JKC_Fallguys/Assets/Resources/Animation/Controller/ResultRoundAnimator/FallGuyAnimator1.controller
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/StageAudioManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/05_RoundResult/RoundResultFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/06_GameResult/GameResultSceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/00_Login/LoginPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Sounds/Music/00_Login.meta
  JKC_Fallguys/Assets/Resources/Sounds/Music/00_Login/MUS_InGame_Jingle.wav
  JKC_Fallguys/Assets/Resources/Sounds/Music/00_Login/MUS_InGame_Jingle.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/Music/04_GameLoading.meta
  JKC_Fallguys/Assets/Resources/Sounds/Music/04_GameLoading/MUS_InGame_Loading.wav
  JKC_Fallguys/Assets/Resources/Sounds/Music/04_GameLoading/MUS_InGame_Loading.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/00_Login.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/00_Login/UI_MainMenu_Login.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/00_Login/UI_MainMenu_Login.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/SFX_WinnerScreen_WinnerAnim.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/SFX_WinnerScreen_WinnerAnim.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Confeti.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Confeti.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Currency_Obtained.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Currency_Obtained.wav.meta
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Numbers_LP.wav
  JKC_Fallguys/Assets/Resources/Sounds/SFX/Result/UI_RewardScreen_Numbers_LP.wav.meta
  JKC_Fallguys/Assets/Tresh/FinalRoundAudioScheduler1.cs
  JKC_Fallguys/Assets/Tresh/FinalRoundAudioScheduler1.cs.meta
  JKC_Fallguys/Assets/Tresh/LobbyAudioScheduler.cs
  JKC_Fallguys/Assets/Tresh/LobbyAudioScheduler.cs.meta
  JKC_Fallguys/Assets/Tresh/RoundAudioScheduler1.cs
  JKC_Fallguys/Assets/Tresh/RoundAudioScheduler1.cs.meta
Labels: enhancement

#361 [Refac] StageDataManager의 플레이어 관련 데이터 분리, PlayerContainer에서 관전 관련 코드 분리
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/ObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#365 [Refac] ResourceManager 정리
  JKC_Fallguys/Assets/1_Scripts/Manager/ResourceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/CountdownSpritesRegistry.cs
  JKC_Fallguys/Assets/1_Scripts/etc/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/MatchingSceneFallguyController.cs
Labels: enhancement

#372 [Refac] PhotonStageRoomManager의 동기화 로직을 PhotonTimeHelper를 이용하여 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs
Labels: enhancement

#374 [Fix] GameResult 씬에서의 승리/패배 에셋이 뜨지 않는 이슈 발생
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/ResultPresenter.cs
Labels: Fix

#376 [Fix] PhotonTimeHelper를 DontDestroyObject로 만들기
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs
Labels: Fix

#377 [Reafac] RoundReult Scene, GameResult Scene전환 로직을 Scene Initializer 스크립트로 리팩토링
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/SceneChanger.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/SceneChanger.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/06_GameResult/AnimationEventController.cs
  JKC_Fallguys/Assets/1_Scripts/etc/06_GameResult/AnimationEventController.cs.meta
  JKC_Fallguys/Assets/Resources/Animation/Controller/GameResultAnimator/VictoryPlayer.controller
  JKC_Fallguys/Assets/Resources/Character/Animation/FG_Idle_Qualification01.anim
  JKC_Fallguys/Assets/Resources/Character/Animation/FG_Idle_Qualification01.anim.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Object/06_GameResult/GameResultSceneFallGuy.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/05_RoundResult/SceneChanger.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/05_RoundResult/SceneChanger.prefab.meta
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#379 [Feat] StageDataManager의 PlayerContainer동적 생성
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/SceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
Labels: enhancement

#381 [Refac] StageRepostiroy 클래스 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonCleaner.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerRepository.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerRepository.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageRepository.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: enhancement

#383 [Fix] Configs UI 팝업 시 이전게임에서 설정한 Volume Value Text로 설정되게 Fix
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/VolumeSettings.cs
Labels: Fix

#386 Jinsoo/#382
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/SceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement, Fix

#389 [Feat] SceneChangeHelper 클래스 구현
  JKC_Fallguys/Assets/1_Scripts/Manager/GameLoadingSceneManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/00_Login/LoginPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper.meta
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/SceneChangeHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/SceneChangeHelper.cs.meta
Labels: enhancement

#397 [Fix] RoundResult 씬에서 4명 이상일 경우 OutOfRange가 발생하는 현상 수정
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Fruit_Scprits.meta
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Fruit_Scprits/CameraController.cs
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Fruit_Scprits/CameraController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Fruit_Scprits/PlayerController.cs
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Fruit_Scprits/PlayerController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/MAP.prefab
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/MAP.prefab.meta
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Purple_1K_Resolution.mat
  JKC_Fallguys/Assets/1_Scripts/etc/FruitMap_Prefabs/Purple_1K_Resolution.mat.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffect.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffect.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffectPool.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffectPool.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffectPooler.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/LineEffectPooler.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/MatchingSceneFallguyController.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/MatchingSceneFallguyController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/ReleaseZone.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/ReleaseZone.cs.meta
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/RespawnZone.cs
  JKC_Fallguys/Assets/1_Scripts/etc/MatchingSceneLineEffect/RespawnZone.cs.meta
Labels: enhancement

#398 [Fix] HoopLegend맵의 외벽 물리 매트릭스 변경
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab
Labels: Fix

#401 [Feat] Stage 씬에서 사용하는 RemainingTime UI 게임이 종료된다면 SetActive False 전환
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
  JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/Customization/CustomizationViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/02_Matching/ExitMatchingPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/03_Stage/StageExitPanelViewController.prefab
Labels: enhancement

#402 [Fix] JumpClub맵의 LowerBar 수정
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/Resources/Materials/Physics/LowerBarPhysicsMaterial.physicMaterial
  JKC_Fallguys/Assets/Resources/Materials/Physics/LowerBarPhysicsMaterial.physicMaterial.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab
Labels: Fix

#405 [Feat] JumpClubController 클래스에 코드 추가
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
Labels: enhancement, Fix

#404 [Refac] Player Dive 물리연산 개선, JumpForce 수치 조정
  JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/States/Jump/JumpSubState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/States/MovementState.cs
  JKC_Fallguys/Assets/3_Art.meta
  JKC_Fallguys/Assets/Resources/Character/Animation/Player.controller
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement

#409 [Feat] Room 입장 제한인원 12명 설정, 각 맵에 SpawnPoint 4개씩 추가
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/3_Art.meta
  JKC_Fallguys/Assets/Resources/Data/MapData_00.json
  JKC_Fallguys/Assets/Resources/Data/MapData_01.json
  JKC_Fallguys/Assets/Resources/Data/MapData_02.json
Labels: enhancement

#410 [Refac] View 클래스를 상속받는 스크립트에서 필요없는 코드 삭제
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigReturnButtonView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlateView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_Matching/ExitMatchingPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/ResultView.cs
  JKC_Fallguys/Assets/Resources/Prefabs/UI/04_GameLoading/MapInformationViewController.prefab
Labels: enhancement

#427 [Refac] Map내에 존재하는 관전카메라 외부로 분리, 데이터로 좌표와 트랜스 폼 지정
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/LandscapeViewer.cs
  JKC_Fallguys/Assets/1_Scripts/Util/MapData.cs
  JKC_Fallguys/Assets/Resources/Data/MapData_00.json
  JKC_Fallguys/Assets/Resources/Data/MapData_01.json
  JKC_Fallguys/Assets/Resources/Data/MapData_02.json
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/LandscapeViewer.prefab
Labels: enhancement

#429 [Refac] 서버에 접속하는 로직 변경
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonInitializeManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonInitializeManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LoginSceneInitializer.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Object/00_Login/PhotonInitializeManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/00_Login/PhotonInitializeManager.prefab.meta
Labels: enhancement

#430 [Fix] jump와 dive키를 동시에 눌렀을때 강한 힘으로 점프하는 현상 해결
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/States/Dive/DiveStartState.cs
  JKC_Fallguys/Assets/1_Scripts/Player/States/Jump/JumpSubState.cs
  JKC_Fallguys/Assets/Resources/Character/Animation/Player.controller
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: Fix

#431 [Fix] HoopLegend 맵에서 게임을 플레이 한 뒤, 점수 업데이트가 마스터 클라이언트만 되는 현상 수정
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
Labels: Fix

#432 [Feat] 카메라 감도를 조절하는 로직 구현
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement

#433 [Fix] 해상도 변경시 Settings UI가 깨지는 현상 해결
  JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/SettingsPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/03_Stage/PurposePanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/03_Stage/RemainingTimeViewController.prefab
Labels: Fix

#434 [Fix] 버튼의 OnSelect에서 CostumeNameText가 변경되게 수정
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs
  JKC_Fallguys/Assets/Resources/ScriptableObject/Grape.asset
  JKC_Fallguys/Assets/Resources/ScriptableObject/Lemon.asset
  JKC_Fallguys/Assets/Resources/ScriptableObject/Melon.asset
  JKC_Fallguys/Assets/Resources/ScriptableObject/Orange.asset
  JKC_Fallguys/Assets/Resources/ScriptableObject/Strawberry.asset
Labels: Fix

#437 [Refac] PhotonStageSceneRoomManager 리팩토링, HoopLegend에서 플레이어의 순위가 제대로 적용되지 않는 현상 Fix
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonCleaner.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonCleaner.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerRepository.cs
  JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/Axe.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/CommonHoop.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/SpecialHoop.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/PhotonStageSceneRoomManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/StageInstantiateManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/04_GameLoading/MapSelectionManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: enhancement, Fix

#438 [Fix] Lobby Scene Fall Guy가 움직일때 다른 UI를 띄우면 움직임을 Cancel하도록 수정
  JKC_Fallguys/Assets/1_Scripts/etc/01_Lobby/LobbySceneFallguyController.cs
  JKC_Fallguys/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#439 [Refac] 룸 동기화 로직 개선
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonInitializeManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
Labels: enhancement

#442 [Fix] 컨베이어가 움직이는 방향으로 플레이어가 움직이는 vector값에 더하게 수정
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/ConveyorBelt.cs
  JKC_Fallguys/Assets/Resources/Materials/FruitChute/ConveyorBeltShaderMaterial.mat
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
  JKC_Fallguys/ProjectSettings/DynamicsManager.asset
Labels: Fix

#443 Jinsoo/#441
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/LandscapeViewer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameCompletion.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameInProgress.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameInProgress.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_RoundCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_RoundCompletion.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RoundEnd/RoundEndPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStart/StageStartPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/GameObjectHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/ScoreCalculateHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/ScoreCalculateHelper.cs.meta
  JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  JKC_Fallguys/Assets/Resources/Sprites/Cursor (1).png
  JKC_Fallguys/Assets/Resources/Sprites/Cursor (1).png.meta
  JKC_Fallguys/Assets/Resources/Sprites/_TestCursor.png
  JKC_Fallguys/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#445 [Style] PhotonStageSceneRoomManager 변경
  JKC_Fallguys/Assets/1_Scripts/Photon/StageStateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/StageStateManager.cs.meta
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/StageStateManager.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/StageStateManager.prefab.meta
Labels: enhancement

#449 [Style] StageState의 AddToDictionary함수를 AddToSequenceActionDictionary로 변경
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameInProgress.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_RoundCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
Labels: enhancement

#450 [Style] 명암이 짙은 현상을 해결
  JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
  JKC_Fallguys/Assets/3_Art.meta
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/FruitChute/MapFruitChute.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab
  JKC_Fallguys/Assets/Resources/Sprites/SkyBox/ColorSkies/Skies/Sky_2.mat
Labels: enhancement

#451 [Feat] Lobby씬에서 Matching 씬으로 전환 시도할 때, Lobby가 아니라면 UI 팝업으로 상태 알리기
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelView.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelView.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelViewController.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelViewController.cs.meta
  JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Resources/Prefabs/UI/00_Login/LoginPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/LobbyConnectionWarningPanelViewController.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/LobbyConnectionWarningPanelViewController.prefab.meta
Labels: enhancement

#456 [Chore] 마우스 감도조정, 오디오 슬라이더 세팅 초기화
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
Labels: chore

#460 [Chore] JumpClub, HoopLegend 바닥 색 변경
  JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
  JKC_Fallguys/Assets/Resources/Materials/HoopLegend/Ground.mat
  JKC_Fallguys/Assets/Resources/Materials/JumpClub/Ground.mat
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
  JKC_Fallguys/ProjectSettings/ProjectSettings.asset
Labels: chore

#461 [Chore] 컨베이어 벨트 밝기 조절, 열기구 메탈릭 조정
  JKC_Fallguys/Assets/Resources/Materials/ConveyorBeltShaderGraph.shadergraph
  JKC_Fallguys/Assets/Resources/Materials/FruitChute/Canon_HotAirBallon.mat
  JKC_Fallguys/Assets/Resources/Materials/FruitChute/ConveyorBeltShaderMaterial.mat
Labels: chore

#463 [Chore] 과일대포 리스폰 벡터 수정, 컨베이어 벨트 밝기 수정
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/2_Scenes/00_Login.unity
  JKC_Fallguys/Assets/Resources/Data/MapData_00.json
  JKC_Fallguys/Assets/Resources/Materials/FruitChute/ConveyorBeltShaderMaterial.mat
  JKC_Fallguys/Assets/Resources/Materials/FruitChute/White_Allow.mat
  JKC_Fallguys/Assets/Resources/Materials/JumpClub/Ground.mat
  JKC_Fallguys/Assets/Resources/Sprites/_Cursor.png
  JKC_Fallguys/Assets/Resources/Sprites/_Cursor.png.meta
  JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#464 [Style] Delete Grab
  JKC_Fallguys/Assets/1_Scripts/Player/States/Grab/AttempingGrabState.cs
Labels: chore

#466 [Chore] Config 해상도 변경
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs
Labels: chore

#469 [Chore] GameResult씬 Background 크기 조절
  JKC_Fallguys/Assets/Resources/Prefabs/UI/06_GameResult/GameResultBackgroundImage.prefab
Labels: chore

#471 [Refac] PhotonTimeHelper 클래스 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/PhotonTimeHelper.prefab
  JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/PhotonTimeHelper.prefab.meta
Labels: enhancement

#473 [Refac] StageManager 코드 리팩토링
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/02_Matching/ExitMatchingPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/HorizontalRendererPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/GameObjectHelper.cs
Labels: enhancement

#475 [Refac] StageDataManager 삭제, ObjectRepository에 로직 병합
  JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
  JKC_Fallguys/Assets/1_Scripts/Photon/StageStateManager.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimationController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs
  JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
  JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/LowerBar.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/LandscapeViewer.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/ObjectRepository.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/ObjectRepository.cs.meta
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/PlayerRepository.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameInProgress.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_RoundCompletion.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
  JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/PurposePanelPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RoundEnd/RoundEndPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStart/StageStartPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
  JKC_Fallguys/Assets/1_Scripts/Util/Helper/ScoreCalculateHelper.cs
Labels: enhancement
